name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
     
    # Imposta la working-directory predefinita per tutti gli step 'run'
    defaults:
      run:
        working-directory: TimeCalculatorApp

    steps:
    - uses: actions/checkout@v4
     
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
     
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17' 
        distribution: 'temurin'
     
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
     
    - name: Install Cordova and dependencies
      run: |
        npm install -g cordova@latest
        npm install

    - name: Remove existing Android Platform (for clean setup)
      # Questo step rimuove la piattaforma Android se esiste, per garantire un'installazione pulita
      # '|| true' impedisce al workflow di fallire se la piattaforma non è già presente
      run: cordova platform rm android --no-save || true

    - name: Add Android Platform
      # Aggiunge la piattaforma Android, che dovrebbe generare i file Gradle wrapper
      run: cordova platform add android

    - name: Prepare Android Project
      # Questo step finalizza la preparazione del progetto dopo l'aggiunta della piattaforma
      run: cordova prepare android

    - name: Make gradlew executable and Build Android APK
      # DEBUG: Aggiunto per listare il contenuto della cartella 'android' prima di usare gradlew
      # Questo ci aiuterà a verificare se gradlew è stato finalmente creato
      run: |
        ls -l ./platforms/android/ 
        # Rende lo script Gradle wrapper eseguibile
        chmod +x ./platforms/android/gradlew
        # Avvia la build dell'APK utilizzando il wrapper Gradle
        ./platforms/android/gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        # Il percorso dell'APK è relativo alla working-directory impostata (TimeCalculatorApp)
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
