name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
     
    # Imposta la working-directory predefinita per tutti gli step 'run'
    # Il repository viene clonato in /home/runner/work/<repo_name>/<repo_name>
    # Se i tuoi file sono in una sottocartella 'TimeCalculatorApp' all'interno della root del repository,
    # allora il percorso relativo sarà semplicemente 'TimeCalculatorApp'.
    defaults:
      run:
        working-directory: TimeCalculatorApp # CORREZIONE: Punti direttamente alla sottocartella del progetto

    steps:
    - uses: actions/checkout@v4
     
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
     
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        # CORREZIONE: Aggiornato da Java 11 a Java 17, come richiesto dallo sdkmanager
        java-version: '17' 
        distribution: 'temurin'
     
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
     
    - name: Install Cordova and dependencies
      # Questo e i successivi comandi 'run' useranno la working-directory definita in 'defaults'
      run: |
        npm install -g cordova@latest
        npm install

    - name: Add Android Platform
      run: cordova platform add android

    - name: Build Android APK
      run: cordova build android --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
        # Il percorso dell'APK è relativo alla working-directory impostata (TimeCalculatorApp),
        # quindi 'platforms/android/...' è corretto se Cordova ha creato le sue sottocartelle lì.
